service:
  name: make-u-happy

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 2048
  stage: ${opt:stage, 'dev'}
  region: "eu-west-1"

functions:
  getPosts:
    handler: src/handlers/getPosts.handler
    events:
      - http:
          method: GET
          path: /posts/{subreddit}
          cors: true
    layers:
      - arn:aws:lambda:eu-west-1:764866452798:layer:chrome-aws-lambda:10
