service:
  name: make-u-happy

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: "eu-west-1"

functions:
  getPosts:
    handler: src/handlers/getPosts.handler
    events:
      - http:
          method: GET
          path: /posts/{subreddit}
